eng_url=https://www.beka-cookware.com/en
dutch_url=https://www.beka-cookware.com/nl
env=prod

#product arguments should be passed to xpath by below parameters for region specific
product_name=Chef frying pan
prdTitleInDutch=Chef braadpan

#Category page xpath paramaters should be passed as per the region
mainCat=Cookware
product=