eng_url=https://www.beka-cookware.com/en
dutch_url=https://www.beka-cookware.com/nl
env=prod
headless=false

#product arguments should be passed to xpath by below parameters for region specific
product_name=Chef frying pan
prdTitleInDutch=Chef braadpan

#Category page xpath paramaters should be passed as per the region
mainCat=Cookware
product=Frying pans

#Below parameter should be passed to get the select drop down for each product
#chef-braadpan - product name should be combined with (-). Example Option1-<productname>
nameOfSelectOption =Option1-chef-braadpan